default:
	g++ ../msg.cpp RTSPServer.cpp RTSPSource.cpp \
	-I/usr/local/include/BasicUsageEnvironment \
	    -I/usr/local/include/groupsock \
	    -I/usr/local/include/liveMedia \
	    -I/usr/local/include/UsageEnvironment \
	    -L/usr/local/lib \
	    -lliveMedia \
	    -lBasicUsageEnvironment \
	    -lgroupsock \
	    -lUsageEnvironment \
	    -o rtspserver
